### ISSUE TITLE
Keep "Working Set" when importing gradle root project

### ISSUE THREAD

**Issue by wolfgang-ch** [de-jcup/egradle#284]
When the feature "Import gradle root project with all subprojects..." is run, then first it removes all already opened/closed Eclipse project from the workspace which are belonging to the gradle root project, but it also removes the projects from all your Eclipse "Working Set"s.

After the projects are opened again then you have to add them all manually to your working sets :-(

**Comment by de-jcup** [comment]
hmm... I could try to check if the projects being closed are in working sets and store this information - after import it would be possible to restore the working set information.

I will try to do this.

**Comment by de-jcup** [comment]
@wolfgang-ch : Now it works. With release 2.1.0 you will get your wanted behaviour, the working sets are rebuild, based on project names. The release will come in the next days.

**Comment by wolfgang-ch** [comment]
This sounds great 👍

**Comment by de-jcup** [comment]
@wolfgang-ch : I just released EGradle 2.1.0 to marketplace...

**Comment by wolfgang-ch** [comment]
Almost perfect, the eclipse projects are displayed again in the working set's 👍 , except one 👎 , the "EGradle - virtual root project" is still not contained in the working set's, which is the most important project :-) (for this feature)
